export const REQUEST_BLACK_CARD = "REQUEST_BLACK_CARD";
export const GET_BLACK_CARD_SUCCESS = "GET_BLACK_CARD_SUCCESS";
export const GET_BLACK_CARD_FAILURE = "GET_BLACK_CARD_FAILURE";
export const REQUEST_WHITE_CARDS="REQUEST_WHITE_CARDS";
export const GET_WHITE_CARDS_SUCCESS = "GET_WHITE_CARDS_SUCCESS";
export const GET_WHITE_CARDS_FAILURE = "GET_WHITE_CARDS_FAILURE";